### ISSUE TITLE
It´s user activate and not user accept

### ISSUE THREAD

**Issue by VitaliKaiser** [polyaxon/polyaxon-docs#3]
Hi,

it seems to be a little overkill for a pull request for only changing one word, but in
polyaxon-docs/templates/management/superusers.md
It says you can activate a new user with "polyaxon user accept <USERNAME>" but actually it´s 
"polyaxon user activate <USERNAME>" 

Best,
Vitali

**Comment by mouradmourafiq** [comment]
Thanks @VitaliKaiser I fixed the issue
